### ISSUE TITLE
Twitter Links Spotty on Review

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/twitter-together#20]
**What happened?**

retweet link was not loading. Not sure if its a twitter/github error, but the link was accurate upon inspection

**What did you expect to happen?**

replicated on two reviewers. Link did not accurately load.

**What the problem might be**

Appears to have self resolved and accurately posted. Just noting for future reviewers.

https://twitter.com/ETC_Network/status/1567935931176321029

**Comment by w1g0** [comment]
This bug should be posted in the original twitter-together repo?

**Comment by IstoraMandiri** [comment]
I believe this is due to @Dexaran 's tweet being formatted incorrectly, see https://github.com/ethereumclassic/twitter-together/pull/23#issuecomment-1241483431
