### ISSUE TITLE
Who has control over what gets tweet and what does not?

### ISSUE THREAD

**Issue by Soteria-Smart-Contracts** [ethereumclassic/twitter-together#21]

**Comment by w1g0** [comment]
It's decided by representatives that have shown contributions to the ETC ecosystem in the past. People can apply to join the approval team.

**Comment by Soteria-Smart-Contracts** [comment]
My firm would like to apply to join the approval team, what are our next steps?

**Comment by w1g0** [comment]
Open a new issue would be the best way to proceed imho.

**Comment by Soteria-Smart-Contracts** [comment]
Okay, thank you. Does a merge require a number of approvals or does it require someone to merge it?

**Comment by w1g0** [comment]
Currently the idea was set to 3 reviewers but that seems not to be on point yet. Once the 3 reviews gave their approval the PR can be merged.

**Comment by Soteria-Smart-Contracts** [comment]
What about a conflict of interest between the party that makes a pull request for a tweet and one of the reviewers? 
@w1g0

**Comment by w1g0** [comment]
The party that creates the pull request cannot review.
There need to be enough diversity among the reviewers to mitigate conflict of interest.

**Comment by Soteria-Smart-Contracts** [comment]
Ok good to hear, closing.
