### ISSUE TITLE
Format issue when using retweet without text

### ISSUE THREAD

**Issue by w1g0** [ethereumclassic/twitter-together#36]
**What happened?**

https://twitter.com/ETC_Network/status/1569703242153750528
https://github.com/ethereumclassic/twitter-together/pull/35

**What did you expect to happen?**

retweet without text

**What the problem might be**

issue in the format

**Comment by w1g0** [comment]
@IstoraMandiri, this seems to be solved and can be closed?

**Comment by IstoraMandiri** [comment]
Closing -> #39
