### ISSUE TITLE
Ability to tweet to multiple accounts from the same repo

### ISSUE THREAD

**Issue by IstoraMandiri** [ethereumclassic/twitter-together#66]
Ref: https://github.com/twitter-together/action/issues/209

**Comment by w1g0** [comment]
I would like to connect https://mastodon.social/web/@Ethereum_Classic to this repo from a GitLab mirror.

**Comment by IstoraMandiri** [comment]
@w1g0 yes, I believe you mention this in #22

**Comment by IstoraMandiri** [comment]
Not needed anymore, as we can create a repo for each account.
